-- work_session_metadata 已在 2026-06-28 泛化并改名为 session_metadata。
-- canonical DDL: database/sessions/session_metadata.sql
-- 旧表迁移方向: ALTER TABLE work_session_metadata RENAME TO session_metadata。
-- 旧 kind 列保留;新读写使用 bound + session_kind + owner_kind / owner_id。
