/*
 * emoji-data.ts — EmojiPicker 的静态数据源(零依赖、纯常量)。
 *
 * 每个分类:稳定的 `key`(代码侧 + i18n 标签键)+ emoji 条目 `[字符, 英文关键词]`。
 * 关键词仅供搜索过滤,既不渲染也不翻译。共计 500+ 条,覆盖 Unicode 主要 emoji 分组。
 * 分类 key 必须与 `settings.agents.icon.picker.category.*` 的 i18n 键一一对应。
 */

export type EmojiEntry = readonly [string, string]
export type EmojiCategory = { readonly key: string; readonly emojis: readonly EmojiEntry[] }

const COMMON: EmojiEntry[] = [
  ['🤖', 'robot bot'],
  ['🙂', 'smile face'],
  ['🚀', 'rocket launch'],
  ['⭐', 'star'],
  ['🔥', 'fire hot'],
  ['💡', 'idea bulb light'],
  ['🧠', 'brain'],
  ['✅', 'check done ok'],
  ['🛠️', 'tools build'],
  ['🎯', 'target goal'],
  ['📌', 'pin'],
  ['🔧', 'wrench tool'],
  ['⚙️', 'gear settings'],
  ['💬', 'chat speech'],
  ['📊', 'chart bar data'],
  ['🧩', 'puzzle piece'],
]

const FACES: EmojiEntry[] = [
  ['😀', 'grin happy'],
  ['😃', 'smiley happy'],
  ['😄', 'smile happy'],
  ['😁', 'beam grin'],
  ['😆', 'laugh squint'],
  ['😅', 'sweat smile'],
  ['🤣', 'rofl laugh'],
  ['😂', 'joy tears laugh'],
  ['🙂', 'slight smile'],
  ['🙃', 'upside down silly'],
  ['😉', 'wink'],
  ['😊', 'blush happy'],
  ['😇', 'angel innocent halo'],
  ['🥰', 'love hearts adore'],
  ['😍', 'heart eyes love'],
  ['🤩', 'star struck'],
  ['😘', 'kiss blow'],
  ['😗', 'kiss'],
  ['😚', 'kiss closed'],
  ['😙', 'kiss smile'],
  ['🥲', 'tear smile'],
  ['😋', 'yum tasty'],
  ['😛', 'tongue'],
  ['😜', 'wink tongue'],
  ['🤪', 'zany goofy'],
  ['😝', 'squint tongue'],
  ['🤑', 'money mouth'],
  ['🤗', 'hug'],
  ['🤭', 'hand mouth giggle'],
  ['🤫', 'shush quiet'],
  ['🤔', 'think'],
  ['🤐', 'zipper mouth'],
  ['🤨', 'raised eyebrow skeptic'],
  ['😐', 'neutral'],
  ['😑', 'expressionless'],
  ['😶', 'no mouth blank'],
  ['😏', 'smirk'],
  ['😒', 'unamused meh'],
  ['🙄', 'eye roll'],
  ['😬', 'grimace'],
  ['🤥', 'lying liar'],
  ['😌', 'relieved calm'],
  ['😔', 'pensive sad'],
  ['😪', 'sleepy'],
  ['🤤', 'drool'],
  ['😴', 'sleep zzz tired'],
  ['😷', 'mask sick'],
  ['🤒', 'thermometer sick'],
  ['🤕', 'bandage hurt'],
  ['🤢', 'nausea sick'],
  ['🤮', 'vomit sick'],
  ['🤧', 'sneeze'],
  ['🥵', 'hot heat'],
  ['🥶', 'cold freeze'],
  ['🥴', 'woozy dizzy'],
  ['😵', 'dizzy knocked'],
  ['🤯', 'mind blown explode'],
  ['🤠', 'cowboy'],
  ['🥳', 'party celebrate'],
  ['🥸', 'disguise glasses'],
  ['😎', 'cool sunglasses'],
  ['🤓', 'nerd geek'],
  ['🧐', 'monocle inspect'],
  ['😕', 'confused'],
  ['😟', 'worried'],
  ['🙁', 'frown slight'],
  ['☹️', 'frown'],
  ['😮', 'open mouth wow'],
  ['😯', 'hushed surprise'],
  ['😲', 'astonished shock'],
  ['😳', 'flushed embarrass'],
  ['🥺', 'pleading puppy'],
  ['😦', 'frown open'],
  ['😧', 'anguished'],
  ['😨', 'fearful scared'],
  ['😰', 'anxious sweat'],
  ['😥', 'sad relieved'],
  ['😢', 'cry tear sad'],
  ['😭', 'sob cry loud'],
  ['😱', 'scream shock fear'],
  ['😖', 'confounded'],
  ['😣', 'persevere'],
  ['😞', 'disappointed'],
  ['😓', 'downcast sweat'],
  ['😩', 'weary tired'],
  ['😫', 'tired exhausted'],
  ['🥱', 'yawn bored'],
  ['😤', 'triumph huff'],
  ['😡', 'rage angry red'],
  ['😠', 'angry mad'],
  ['🤬', 'curse swear'],
  ['😈', 'devil imp'],
  ['👿', 'devil angry'],
  ['💀', 'skull dead'],
  ['☠️', 'skull crossbones'],
  ['💩', 'poop'],
  ['🤡', 'clown'],
  ['👹', 'ogre monster'],
  ['👺', 'goblin'],
  ['👻', 'ghost'],
  ['👽', 'alien'],
  ['👾', 'alien invader game'],
  ['🎃', 'pumpkin halloween'],
  ['😺', 'cat smile'],
  ['😸', 'cat grin'],
  ['😹', 'cat joy'],
  ['😻', 'cat heart eyes'],
  ['😼', 'cat smirk'],
  ['😽', 'cat kiss'],
  ['🙀', 'cat weary'],
  ['😿', 'cat cry'],
  ['😾', 'cat pouting'],
]

const PEOPLE: EmojiEntry[] = [
  ['👋', 'wave hand hello'],
  ['🤚', 'raised back hand'],
  ['🖐️', 'hand fingers'],
  ['✋', 'raised hand stop'],
  ['🖖', 'vulcan spock'],
  ['👌', 'ok hand'],
  ['🤌', 'pinch fingers'],
  ['🤏', 'pinch small'],
  ['✌️', 'victory peace'],
  ['🤞', 'crossed fingers luck'],
  ['🤟', 'love you gesture'],
  ['🤘', 'rock horns'],
  ['🤙', 'call me'],
  ['👈', 'point left'],
  ['👉', 'point right'],
  ['👆', 'point up'],
  ['👇', 'point down'],
  ['☝️', 'index up'],
  ['👍', 'thumbs up like'],
  ['👎', 'thumbs down dislike'],
  ['✊', 'fist raised'],
  ['👊', 'fist punch'],
  ['🤛', 'fist left'],
  ['🤜', 'fist right'],
  ['👏', 'clap applause'],
  ['🙌', 'raise hands praise'],
  ['👐', 'open hands'],
  ['🤲', 'palms up'],
  ['🤝', 'handshake deal'],
  ['🙏', 'pray thanks please'],
  ['✍️', 'write hand'],
  ['💅', 'nail polish'],
  ['🤳', 'selfie'],
  ['💪', 'muscle strong flex'],
  ['🦾', 'mechanical arm'],
  ['🦿', 'mechanical leg'],
  ['🦵', 'leg'],
  ['🦶', 'foot'],
  ['👂', 'ear'],
  ['👃', 'nose'],
  ['🧠', 'brain'],
  ['🫀', 'heart organ'],
  ['🫁', 'lungs'],
  ['🦷', 'tooth'],
  ['🦴', 'bone'],
  ['👀', 'eyes look'],
  ['👁️', 'eye'],
  ['👅', 'tongue'],
  ['👄', 'mouth lips'],
  ['👶', 'baby'],
  ['🧒', 'child kid'],
  ['👦', 'boy'],
  ['👧', 'girl'],
  ['🧑', 'person adult'],
  ['👨', 'man'],
  ['👩', 'woman'],
  ['🧓', 'older person'],
  ['👴', 'old man grandpa'],
  ['👵', 'old woman grandma'],
  ['🙋', 'raise hand question'],
  ['🙆', 'ok gesture'],
  ['🙅', 'no gesture forbidden'],
  ['💁', 'info desk tipping'],
  ['🙇', 'bow sorry'],
  ['🤦', 'facepalm'],
  ['🤷', 'shrug dunno'],
  ['🧑‍💻', 'developer coder programmer'],
  ['👩‍🔬', 'scientist woman'],
  ['🧑‍🔬', 'scientist'],
  ['🕵️', 'detective spy'],
  ['🧙', 'wizard mage'],
  ['🦸', 'hero super'],
  ['🦹', 'villain supervillain'],
  ['👨‍🏫', 'teacher man'],
  ['🧑‍🏫', 'teacher'],
  ['🧑‍🚀', 'astronaut'],
  ['👷', 'worker construction'],
  ['🧑‍⚖️', 'judge law'],
  ['🥷', 'ninja'],
  ['🤴', 'prince'],
  ['👸', 'princess'],
  ['🧑‍🍳', 'chef cook'],
  ['🧑‍🚒', 'firefighter'],
  ['🧑‍✈️', 'pilot'],
  ['💂', 'guard'],
  ['🎅', 'santa claus'],
  ['🧝', 'elf'],
  ['🧚', 'fairy'],
  ['🧛', 'vampire'],
  ['🧟', 'zombie'],
  ['🚶', 'walk pedestrian'],
  ['🏃', 'run runner'],
  ['💃', 'dance woman'],
  ['🕺', 'dance man'],
]

const ANIMALS: EmojiEntry[] = [
  ['🐶', 'dog puppy'],
  ['🐱', 'cat'],
  ['🐭', 'mouse'],
  ['🐹', 'hamster'],
  ['🐰', 'rabbit bunny'],
  ['🦊', 'fox'],
  ['🐻', 'bear'],
  ['🐼', 'panda'],
  ['🐻‍❄️', 'polar bear'],
  ['🐨', 'koala'],
  ['🐯', 'tiger'],
  ['🦁', 'lion'],
  ['🐮', 'cow'],
  ['🐷', 'pig'],
  ['🐽', 'pig nose'],
  ['🐸', 'frog'],
  ['🐵', 'monkey'],
  ['🙈', 'see no evil monkey'],
  ['🙉', 'hear no evil monkey'],
  ['🙊', 'speak no evil monkey'],
  ['🐒', 'monkey'],
  ['🐔', 'chicken'],
  ['🐧', 'penguin'],
  ['🐦', 'bird'],
  ['🐤', 'baby chick'],
  ['🦅', 'eagle'],
  ['🦆', 'duck'],
  ['🦉', 'owl'],
  ['🦇', 'bat'],
  ['🐺', 'wolf'],
  ['🐗', 'boar'],
  ['🐴', 'horse face'],
  ['🦄', 'unicorn'],
  ['🐝', 'bee honeybee'],
  ['🐛', 'bug caterpillar'],
  ['🦋', 'butterfly'],
  ['🐌', 'snail'],
  ['🐞', 'ladybug'],
  ['🐜', 'ant'],
  ['🦗', 'cricket'],
  ['🕷️', 'spider'],
  ['🦂', 'scorpion'],
  ['🐢', 'turtle'],
  ['🐍', 'snake'],
  ['🦎', 'lizard'],
  ['🦖', 'trex dinosaur'],
  ['🦕', 'sauropod dinosaur'],
  ['🐙', 'octopus'],
  ['🦑', 'squid'],
  ['🦐', 'shrimp'],
  ['🦞', 'lobster'],
  ['🦀', 'crab'],
  ['🐡', 'blowfish'],
  ['🐠', 'tropical fish'],
  ['🐟', 'fish'],
  ['🐬', 'dolphin'],
  ['🐳', 'whale spout'],
  ['🐋', 'whale'],
  ['🦈', 'shark'],
  ['🐊', 'crocodile'],
  ['🐅', 'tiger'],
  ['🐆', 'leopard'],
  ['🦓', 'zebra'],
  ['🦍', 'gorilla'],
  ['🦧', 'orangutan'],
  ['🐘', 'elephant'],
  ['🦏', 'rhino'],
  ['🦛', 'hippo'],
  ['🐪', 'camel'],
  ['🦒', 'giraffe'],
  ['🦘', 'kangaroo'],
  ['🐃', 'buffalo'],
  ['🐂', 'ox'],
  ['🐄', 'cow'],
  ['🐎', 'horse racing'],
  ['🐖', 'pig'],
  ['🐏', 'ram'],
  ['🐑', 'sheep'],
  ['🦙', 'llama'],
  ['🐐', 'goat'],
  ['🦌', 'deer'],
  ['🐕', 'dog'],
  ['🐩', 'poodle'],
  ['🐈', 'cat'],
  ['🐓', 'rooster'],
  ['🦃', 'turkey'],
  ['🦚', 'peacock'],
  ['🦜', 'parrot'],
  ['🦢', 'swan'],
  ['🕊️', 'dove peace'],
  ['🐇', 'rabbit'],
  ['🦝', 'raccoon'],
  ['🦨', 'skunk'],
  ['🦡', 'badger'],
  ['🦦', 'otter'],
  ['🦥', 'sloth'],
  ['🐁', 'mouse'],
  ['🐀', 'rat'],
  ['🐿️', 'chipmunk squirrel'],
  ['🦔', 'hedgehog'],
  ['🌸', 'blossom flower'],
  ['🌹', 'rose'],
  ['🌻', 'sunflower'],
  ['🌷', 'tulip'],
  ['🌼', 'daisy flower'],
  ['🌺', 'hibiscus'],
  ['🌳', 'tree'],
  ['🌲', 'evergreen tree'],
  ['🌴', 'palm tree'],
  ['🌵', 'cactus'],
  ['🍀', 'clover luck'],
  ['🍁', 'maple leaf'],
  ['🍃', 'leaves wind'],
  ['🌿', 'herb plant'],
  ['🌱', 'seedling sprout'],
]

const FOOD: EmojiEntry[] = [
  ['🍎', 'apple red'],
  ['🍏', 'apple green'],
  ['🍐', 'pear'],
  ['🍊', 'orange tangerine'],
  ['🍋', 'lemon'],
  ['🍌', 'banana'],
  ['🍉', 'watermelon'],
  ['🍇', 'grapes'],
  ['🍓', 'strawberry'],
  ['🫐', 'blueberries'],
  ['🍈', 'melon'],
  ['🍒', 'cherries'],
  ['🍑', 'peach'],
  ['🥭', 'mango'],
  ['🍍', 'pineapple'],
  ['🥥', 'coconut'],
  ['🥝', 'kiwi'],
  ['🍅', 'tomato'],
  ['🍆', 'eggplant aubergine'],
  ['🥑', 'avocado'],
  ['🥦', 'broccoli'],
  ['🥬', 'leafy green'],
  ['🥒', 'cucumber'],
  ['🌶️', 'chili pepper hot'],
  ['🌽', 'corn'],
  ['🥕', 'carrot'],
  ['🧄', 'garlic'],
  ['🧅', 'onion'],
  ['🥔', 'potato'],
  ['🍠', 'sweet potato'],
  ['🥐', 'croissant'],
  ['🥯', 'bagel'],
  ['🍞', 'bread'],
  ['🥖', 'baguette'],
  ['🥨', 'pretzel'],
  ['🧀', 'cheese'],
  ['🥚', 'egg'],
  ['🍳', 'fried egg cooking'],
  ['🧈', 'butter'],
  ['🥞', 'pancakes'],
  ['🧇', 'waffle'],
  ['🥓', 'bacon'],
  ['🥩', 'steak meat'],
  ['🍗', 'poultry leg chicken'],
  ['🍖', 'meat bone'],
  ['🌭', 'hotdog'],
  ['🍔', 'burger hamburger'],
  ['🍟', 'fries'],
  ['🍕', 'pizza'],
  ['🥪', 'sandwich'],
  ['🌮', 'taco'],
  ['🌯', 'burrito'],
  ['🥙', 'pita stuffed'],
  ['🧆', 'falafel'],
  ['🥘', 'paella pan'],
  ['🍝', 'spaghetti pasta'],
  ['🍜', 'ramen noodles'],
  ['🍲', 'stew pot'],
  ['🍛', 'curry rice'],
  ['🍣', 'sushi'],
  ['🍱', 'bento box'],
  ['🍤', 'fried shrimp tempura'],
  ['🍙', 'rice ball onigiri'],
  ['🍚', 'rice'],
  ['🍘', 'rice cracker'],
  ['🥟', 'dumpling'],
  ['🍢', 'oden'],
  ['🍡', 'dango'],
  ['🍧', 'shaved ice'],
  ['🍨', 'ice cream'],
  ['🍦', 'soft serve'],
  ['🥧', 'pie'],
  ['🧁', 'cupcake'],
  ['🍰', 'cake slice'],
  ['🎂', 'birthday cake'],
  ['🍮', 'custard pudding'],
  ['🍭', 'lollipop'],
  ['🍬', 'candy'],
  ['🍫', 'chocolate'],
  ['🍿', 'popcorn'],
  ['🍩', 'donut'],
  ['🍪', 'cookie'],
  ['☕', 'coffee tea hot'],
  ['🍵', 'tea green'],
  ['🧃', 'juice box'],
  ['🥤', 'soda cup drink'],
  ['🧋', 'bubble tea'],
  ['🍺', 'beer'],
  ['🍻', 'beers cheers'],
  ['🍷', 'wine'],
  ['🥂', 'champagne toast'],
  ['🍸', 'cocktail martini'],
  ['🍹', 'tropical drink'],
  ['🥃', 'whiskey glass'],
  ['🍾', 'champagne bottle'],
]

const TRAVEL: EmojiEntry[] = [
  ['🚗', 'car automobile'],
  ['🚕', 'taxi'],
  ['🚙', 'suv car'],
  ['🚌', 'bus'],
  ['🚎', 'trolleybus'],
  ['🏎️', 'race car'],
  ['🚓', 'police car'],
  ['🚑', 'ambulance'],
  ['🚒', 'fire truck'],
  ['🚐', 'minibus van'],
  ['🛻', 'pickup truck'],
  ['🚚', 'delivery truck'],
  ['🚛', 'lorry truck'],
  ['🚜', 'tractor'],
  ['🏍️', 'motorcycle'],
  ['🛵', 'scooter'],
  ['🚲', 'bicycle bike'],
  ['🛴', 'kick scooter'],
  ['🚂', 'train locomotive'],
  ['🚆', 'train'],
  ['🚄', 'bullet train'],
  ['🚅', 'shinkansen train'],
  ['🚈', 'light rail'],
  ['🚇', 'metro subway'],
  ['🚊', 'tram'],
  ['🚝', 'monorail'],
  ['🚞', 'mountain railway'],
  ['🚋', 'tram car'],
  ['✈️', 'airplane flight'],
  ['🛫', 'departure plane'],
  ['🛬', 'arrival plane'],
  ['🛩️', 'small plane'],
  ['🚁', 'helicopter'],
  ['🚀', 'rocket'],
  ['🛸', 'ufo saucer'],
  ['🛰️', 'satellite'],
  ['⛵', 'sailboat'],
  ['🚤', 'speedboat'],
  ['🛥️', 'motor boat'],
  ['🚢', 'ship'],
  ['⛴️', 'ferry'],
  ['🛳️', 'cruise ship'],
  ['⚓', 'anchor'],
  ['🚉', 'station'],
  ['🚏', 'bus stop'],
  ['🚦', 'traffic light'],
  ['🚥', 'traffic signal'],
  ['🗺️', 'map world'],
  ['🧭', 'compass'],
  ['🏔️', 'mountain snow'],
  ['⛰️', 'mountain'],
  ['🌋', 'volcano'],
  ['🗻', 'fuji mountain'],
  ['🏕️', 'camping tent'],
  ['🏖️', 'beach umbrella'],
  ['🏜️', 'desert'],
  ['🏝️', 'island'],
  ['🏞️', 'park nature'],
  ['🏟️', 'stadium'],
  ['🏛️', 'classical building'],
  ['🏗️', 'construction crane'],
  ['🏠', 'house home'],
  ['🏡', 'house garden'],
  ['🏢', 'office building'],
  ['🏣', 'post office japan'],
  ['🏥', 'hospital'],
  ['🏦', 'bank'],
  ['🏨', 'hotel'],
  ['🏪', 'convenience store'],
  ['🏫', 'school'],
  ['🏩', 'love hotel'],
  ['💒', 'wedding chapel'],
  ['🏰', 'castle'],
  ['🏯', 'japanese castle'],
  ['🗼', 'tower tokyo'],
  ['🗽', 'statue liberty'],
  ['⛪', 'church'],
  ['🕌', 'mosque'],
  ['🛕', 'hindu temple'],
  ['🕍', 'synagogue'],
  ['⛩️', 'shrine torii'],
  ['🌁', 'foggy city'],
  ['🌃', 'night stars city'],
  ['🌆', 'dusk city'],
  ['🌇', 'sunset city'],
  ['🌉', 'bridge night'],
  ['🏙️', 'cityscape skyline'],
  ['🎡', 'ferris wheel'],
  ['🎢', 'roller coaster'],
  ['🎠', 'carousel'],
]

const ACTIVITIES: EmojiEntry[] = [
  ['⚽', 'soccer football'],
  ['🏀', 'basketball'],
  ['🏈', 'american football'],
  ['⚾', 'baseball'],
  ['🥎', 'softball'],
  ['🎾', 'tennis'],
  ['🏐', 'volleyball'],
  ['🏉', 'rugby'],
  ['🥏', 'frisbee disc'],
  ['🎱', 'pool 8 ball'],
  ['🪀', 'yoyo'],
  ['🏓', 'ping pong table tennis'],
  ['🏸', 'badminton'],
  ['🏒', 'hockey'],
  ['🏑', 'field hockey'],
  ['🥍', 'lacrosse'],
  ['🏏', 'cricket bat'],
  ['🥅', 'goal net'],
  ['⛳', 'golf flag'],
  ['🏹', 'bow arrow archery'],
  ['🎣', 'fishing'],
  ['🥊', 'boxing glove'],
  ['🥋', 'martial arts'],
  ['🎽', 'running shirt'],
  ['🛹', 'skateboard'],
  ['🛼', 'roller skate'],
  ['⛸️', 'ice skate'],
  ['🥌', 'curling'],
  ['🎿', 'ski'],
  ['⛷️', 'skier'],
  ['🏂', 'snowboard'],
  ['🪂', 'parachute'],
  ['🏋️', 'weightlift gym'],
  ['🤸', 'cartwheel gymnastics'],
  ['🤼', 'wrestling'],
  ['🤽', 'water polo'],
  ['🤾', 'handball'],
  ['🤺', 'fencing'],
  ['🏇', 'horse racing'],
  ['🧘', 'yoga meditate'],
  ['🏄', 'surfing'],
  ['🏊', 'swimming'],
  ['🚣', 'rowing'],
  ['🧗', 'climbing'],
  ['🚵', 'mountain biking'],
  ['🚴', 'cycling'],
  ['🏆', 'trophy win'],
  ['🥇', 'gold medal first'],
  ['🥈', 'silver medal second'],
  ['🥉', 'bronze medal third'],
  ['🏅', 'medal sports'],
  ['🎖️', 'military medal'],
  ['🎮', 'game controller'],
  ['🕹️', 'joystick'],
  ['🎲', 'dice'],
  ['♟️', 'chess pawn'],
  ['🎯', 'dart target'],
  ['🎳', 'bowling'],
  ['🎰', 'slot machine'],
  ['🎨', 'art palette paint'],
  ['🎭', 'theater masks'],
  ['🎤', 'microphone sing'],
  ['🎧', 'headphones'],
  ['🎼', 'music score'],
  ['🎹', 'piano keyboard'],
  ['🥁', 'drum'],
  ['🎷', 'saxophone'],
  ['🎺', 'trumpet'],
  ['🎸', 'guitar'],
  ['🎻', 'violin'],
  ['🪕', 'banjo'],
]

const OBJECTS: EmojiEntry[] = [
  ['⌚', 'watch time'],
  ['📱', 'phone mobile'],
  ['💻', 'laptop computer'],
  ['⌨️', 'keyboard'],
  ['🖥️', 'desktop monitor'],
  ['🖨️', 'printer'],
  ['🖱️', 'mouse computer'],
  ['🖲️', 'trackball'],
  ['💽', 'minidisc'],
  ['💾', 'floppy save disk'],
  ['💿', 'cd disc'],
  ['📀', 'dvd disc'],
  ['🧮', 'abacus'],
  ['🎥', 'movie camera'],
  ['📷', 'camera photo'],
  ['📸', 'camera flash'],
  ['📹', 'video camera'],
  ['📼', 'videotape'],
  ['🔍', 'search magnify'],
  ['🔎', 'magnify right'],
  ['🔬', 'microscope'],
  ['🔭', 'telescope'],
  ['📡', 'satellite antenna'],
  ['🕯️', 'candle'],
  ['💡', 'bulb light idea'],
  ['🔦', 'flashlight'],
  ['🏮', 'lantern'],
  ['📔', 'notebook decorated'],
  ['📕', 'closed book'],
  ['📖', 'open book'],
  ['📗', 'green book'],
  ['📘', 'blue book'],
  ['📚', 'books library'],
  ['📓', 'notebook'],
  ['📒', 'ledger'],
  ['📃', 'page document'],
  ['📜', 'scroll'],
  ['📄', 'document page'],
  ['📰', 'newspaper'],
  ['📑', 'bookmark tabs'],
  ['🔖', 'bookmark'],
  ['🏷️', 'label tag'],
  ['💰', 'money bag'],
  ['🪙', 'coin'],
  ['💵', 'dollar cash'],
  ['💳', 'credit card'],
  ['🧾', 'receipt'],
  ['✉️', 'envelope mail'],
  ['📧', 'email'],
  ['📨', 'incoming mail'],
  ['📩', 'mail arrow'],
  ['📦', 'package box'],
  ['📫', 'mailbox'],
  ['📮', 'postbox'],
  ['✏️', 'pencil'],
  ['✒️', 'pen nib'],
  ['🖊️', 'pen'],
  ['🖋️', 'fountain pen'],
  ['🖌️', 'paintbrush'],
  ['🖍️', 'crayon'],
  ['📝', 'memo note write'],
  ['📁', 'folder'],
  ['📂', 'open folder'],
  ['🗂️', 'card index folders'],
  ['📅', 'calendar date'],
  ['📆', 'calendar tear'],
  ['📇', 'card index'],
  ['📈', 'chart up trend'],
  ['📉', 'chart down trend'],
  ['📊', 'bar chart data'],
  ['📋', 'clipboard'],
  ['📌', 'pushpin'],
  ['📍', 'round pin location'],
  ['📎', 'paperclip'],
  ['📏', 'ruler straight'],
  ['📐', 'triangle ruler'],
  ['✂️', 'scissors cut'],
  ['🗃️', 'card file box'],
  ['🗄️', 'file cabinet'],
  ['🗑️', 'trash bin delete'],
  ['🔒', 'lock secure'],
  ['🔓', 'unlock open'],
  ['🔏', 'lock pen'],
  ['🔐', 'lock key'],
  ['🔑', 'key'],
  ['🗝️', 'old key'],
  ['🔨', 'hammer'],
  ['🪓', 'axe'],
  ['⛏️', 'pick mining'],
  ['🔩', 'nut bolt'],
  ['🧰', 'toolbox'],
  ['🧲', 'magnet'],
  ['⚗️', 'alembic chemistry'],
  ['🧪', 'test tube lab'],
  ['🧫', 'petri dish'],
  ['🧬', 'dna'],
  ['💊', 'pill medicine'],
  ['💉', 'syringe shot'],
  ['🩺', 'stethoscope'],
  ['🌡️', 'thermometer'],
  ['🧹', 'broom clean'],
  ['🧺', 'basket'],
  ['🧻', 'toilet paper roll'],
  ['🚽', 'toilet'],
  ['🚿', 'shower'],
  ['🛁', 'bathtub'],
  ['🪒', 'razor'],
  ['🧼', 'soap'],
  ['🪥', 'toothbrush'],
  ['🛒', 'shopping cart'],
]

const SYMBOLS: EmojiEntry[] = [
  ['❤️', 'heart love red'],
  ['🧡', 'orange heart'],
  ['💛', 'yellow heart'],
  ['💚', 'green heart'],
  ['💙', 'blue heart'],
  ['💜', 'purple heart'],
  ['🖤', 'black heart'],
  ['🤍', 'white heart'],
  ['🤎', 'brown heart'],
  ['💔', 'broken heart'],
  ['❣️', 'heart exclamation'],
  ['💕', 'two hearts'],
  ['💞', 'revolving hearts'],
  ['💓', 'beating heart'],
  ['💗', 'growing heart'],
  ['💖', 'sparkle heart'],
  ['💘', 'heart arrow cupid'],
  ['💝', 'heart gift ribbon'],
  ['💟', 'heart decoration'],
  ['☮️', 'peace'],
  ['✝️', 'cross latin'],
  ['☪️', 'star crescent'],
  ['🕉️', 'om hindu'],
  ['☸️', 'dharma wheel'],
  ['✡️', 'star david'],
  ['🔯', 'six pointed star'],
  ['☯️', 'yin yang'],
  ['♈', 'aries zodiac'],
  ['♉', 'taurus zodiac'],
  ['♊', 'gemini zodiac'],
  ['♋', 'cancer zodiac'],
  ['♌', 'leo zodiac'],
  ['♍', 'virgo zodiac'],
  ['♎', 'libra zodiac'],
  ['♏', 'scorpio zodiac'],
  ['♐', 'sagittarius zodiac'],
  ['♑', 'capricorn zodiac'],
  ['♒', 'aquarius zodiac'],
  ['♓', 'pisces zodiac'],
  ['⛎', 'ophiuchus zodiac'],
  ['🆔', 'id button'],
  ['⚛️', 'atom science'],
  ['🉑', 'accept button'],
  ['☢️', 'radioactive'],
  ['☣️', 'biohazard'],
  ['📴', 'phone off'],
  ['📳', 'vibration'],
  ['♻️', 'recycle'],
  ['⚜️', 'fleur de lis'],
  ['🔱', 'trident'],
  ['📛', 'name badge'],
  ['⭕', 'circle red'],
  ['✅', 'check green'],
  ['☑️', 'checkbox'],
  ['✔️', 'check mark'],
  ['❌', 'cross x'],
  ['❎', 'cross button'],
  ['➕', 'plus add'],
  ['➖', 'minus subtract'],
  ['➗', 'divide'],
  ['✖️', 'multiply'],
  ['♾️', 'infinity'],
  ['‼️', 'double exclamation'],
  ['⁉️', 'exclamation question'],
  ['❓', 'question mark'],
  ['❔', 'white question'],
  ['❗', 'exclamation'],
  ['❕', 'white exclamation'],
  ['〰️', 'wavy dash'],
  ['⚠️', 'warning caution'],
  ['🚸', 'children crossing'],
  ['🔰', 'beginner novice'],
  ['💯', 'hundred perfect'],
  ['✨', 'sparkles'],
  ['⚡', 'lightning bolt'],
  ['💥', 'collision boom'],
  ['💫', 'dizzy star'],
  ['⭐', 'star'],
  ['🌟', 'glowing star'],
  ['💎', 'gem diamond'],
  ['🔔', 'bell notify'],
  ['🔕', 'bell off mute'],
  ['🎵', 'music note'],
  ['🎶', 'music notes'],
  ['🔵', 'blue circle'],
  ['🟢', 'green circle'],
  ['🔴', 'red circle'],
  ['🟡', 'yellow circle'],
  ['🟣', 'purple circle'],
  ['🟠', 'orange circle'],
  ['⚫', 'black circle'],
  ['⚪', 'white circle'],
  ['🟥', 'red square'],
  ['🟦', 'blue square'],
  ['🟩', 'green square'],
  ['🟨', 'yellow square'],
]

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  { key: 'common', emojis: COMMON },
  { key: 'faces', emojis: FACES },
  { key: 'people', emojis: PEOPLE },
  { key: 'animals', emojis: ANIMALS },
  { key: 'food', emojis: FOOD },
  { key: 'travel', emojis: TRAVEL },
  { key: 'activities', emojis: ACTIVITIES },
  { key: 'objects', emojis: OBJECTS },
  { key: 'symbols', emojis: SYMBOLS },
]
